### ISSUE TITLE
SSL certificate on local-ip.sh expired

### ISSUE THREAD

**Issue by Seblor** [m5r/local-ip.sh#2]
Hello !

The SSL certificate for local-ip.sh seems to have expired a few hours ago, did something happen with the auto-renewal process ?

**Comment by m5r** [comment]
Hello, sorry for the downtime and thanks for the notification. There was an issue with the certificate request for the root domain where it wasn't getting properly renewed. It's now fixed and the website is back online. I'm working on a more durable fix and I'll push the changes when ready.
